---
# Title The Pages
title:       CahBot Discord Bot
# The name of the repository
repotitle:   CahBot
# Description
description: A Discord bot that’s kinda cool that’s being updated frequently, written in Ruby
# Author
author:      The CB Team
# Author URL
authorurl:   http://github.com/Cahbots
# URL to the page. Usually https://orgname.github.io (put whatever's in the CNAME otherwise)
url:         https://ruby.cahbot.pro
